config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
      member do
      get 'followings'
      get 'followers'
      get 'favorites'
    end
    end
  resources :hikes
  resources :relationships, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites,     only: [:create, :destroy]
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorite, class_name: "Hike"
end

app/models/hike.rb
class Hike < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 7 }
  validates :content2, presence: true, length: { maximum: 9 }
  validates :content3, presence: true, length: { maximum: 7 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :hikes
    has_many :favorites, foreign_key: "user_id", dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :favorite
    has_many :following_relationships, class_name: "Relationship",
                                        foreign_key: "follower_id",
                                        dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    has_many :follower_relationships, class_name: "Relationship",
                                        foreign_key: "followed_id",
                                        dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower


    # 他のユーザーをフォローする
    def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
    end

    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
    end

  # あるユーザーをフォローしているかどうか？
    def following?(other_user)
    following_users.include?(other_user)
    end
    
  # favorite
    def favorite(hike)
        favorites.find_or_create_by(favorite_id: hike.id)
    end
    
    def unfavorite(hike)
        fav =favorites.find_by(favorite_id: hike.id)
        fav.destroy if fav != nil
    end
    
    def favorite?(hike)
        favorite_posts.include?(hike)
    end
    
    def favorite_items
    Hike.where(hike_id: favorite_ids)
    end
    
    def feed_items
    Hike.where(user_id: following_user_ids + [self.id])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインはこちら"
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :logged_in_user
    
    def create
        @hike = Hike.find(params[:hike_id])
        current_user.favorite(@hike)
    end
    
    def destroy
        @favorite = Favorite.find(params[:id])
        @hike = @favorite.favorite
        current_user.unfavorite(@hike)
    end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
    before_action :logged_in_user, only: [:create]

    def create
    @hike = current_user.hikes.build(hike_params)
        if @hike.save
        flash[:success] = "Yonda!"
        redirect_to root_url
        else
        @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
        render 'static_pages/home'
        end
    end

  def destroy
    @hike = current_user.hikes.find_by(id: params[:id])
    return redirect_to root_url if @hike.nil?
    @hike.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end
  
    def favorite
    @hike = hikes.find_by(id: params[:id])
    @hike.favorite
    flash[:success] = "iiku!しました"
    return redirect_to root_url
    
    @favorite_items = current_user.favorite_items.includes(:user).order(created at: :desc)
    render 'static_pages/favorite'
    end
  
    private
        def hike_params
        params.require(:hike).permit(:content, :content2, :content3, :description)
        end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

    def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    end

    def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @hike = current_user.hikes.build if logged_in?
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:edit, :update]
before_action :check_user,     only: [:edit, :update]
  
  def show
   @user = User.find(params[:id])
   @hikes = @user.hikes.order(created_at: :desc)
  end
  
  def new
  @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Hikesへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end
  
   # edit_user GET    /users/:id/edit(.:format) users#edit
  def edit
    @user = User.find(params[:id])
    # @user は編集対象のユーザー
    # current_user はログインしているユーザー    

  end
  
  def update
    if (@user.update(user_profile))
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "更新できませんでした"
      render "edit"
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @f_user = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @fs_user = @user.follower_users
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_posts
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def user_profile
    params.require(:user).permit(:name, :email, :profile)
  end
  
  def check_user
    @user = User.find(params[:id])
    if (current_user != @user)
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/favorites/create.js.erb
$("#favorite-<%= @hike.id %>").html("<%= escape_javascript(render('hikes/unfavorite', hike:@hike)) %>");

app/views/favorites/destroy.js.erb
$("#favorite-<%= @hike.id %>").html("<%= escape_javascript(render('hikes/favorite', hike:@hike)) %>");

app/views/hikes/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>

<div>
    <%= hidden_field_tag :hike_id, hike.id %>
</div>
<%#= f.submit %Q!<span class="glyphicon glyphicon-heart"></span>!, class: "btn btn-default" %>
<div id="favorite"><%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <span class="glyphicon glyphicon-heart heart-white"></span>
    <% end %>
</div>
<% end %>

app/views/hikes/_hike.html.erb
<li id="hike-<%= hike.id %>">
  <%= link_to gravatar_for(hike.user, size: 50), hike.user %>
  <span class="user"><%= link_to hike.user.name, hike.user %></span>
  <% if current_user == hike.user %>
      <%= link_to sanitize('<span class="glyphicon glyphicon-trash"></span>'), hike, method: :delete,
                                       data: { confirm: "削除してもよろしいですか？" } %>
  <% end %>
  <span class="content"><%= hike.content %></br><%= hike.content2 %></br> <%= hike.content3 %></span>
  <span class="timestamp">
    <%= hike.created_at.strftime("%Y年%m月%d日 %H:%M") %>
  </span>
    <% if logged_in? %>
    <div id="favorite-<%= hike.id %>">
    <% if current_user.favorite?(hike) %>
        <%= render 'hikes/unfavorite' , hike: hike %>
         <%# お気に入り済み %>
    <% else %>
         <%= render 'hikes/favorite' , hike: hike %>
    <% end %>
    <% end %>
  
</li>

app/views/hikes/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(favorite_id: hike.id),
            html: { method: :delete },
            remote: true) do |f| %>

<div><%= hidden_field_tag :hike_id, hike.id %></div>
<%#= f.submit sanitize('<span class="glyphicon glyphicon-heart pink"></span>'), class: "btn btn-default" %>
<div id="unfavorite"><%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <span class="glyphicon glyphicon-heart pink"></span>
    <% end %>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <div id="logo">
       <%= image_tag 'logo.png', :alt => 'hikes-logo' %>
      </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to sanitize('<span class="glyphicon glyphicon-home"></span>'), root_path %></li>
        <% if logged_in? %>
          <li><%= link_to sanitize('<span class="glyphicon glyphicon-heart"></span>'), favorites_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-align-justify"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィールの編集", edit_user_path(current_user) %></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hikes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="hikes">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_hike_form.html.erb
<%= form_for(@hike) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "上の句" %>
    <%= f.text_area :content2, placeholder: "中の句"%>
    <%= f.text_area :content3, placeholder: "下の句"%>
  </div>
  <%= f.submit "Hike!", class: "btn btn-warning" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを見る", current_user %></span>
<span><%= pluralize(current_user.hikes.count, "hike") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="hike_form">
        <%= render 'shared/hike_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>みんなのHike</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Hikesへようこそ</h1>

    <%= link_to "Hikeに登録する", signup_path, class: "btn btn-lg btn-warning" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-default" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォローしています", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィールを編集する</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render'shared/error_messages' , object: f.object %>
        
        <%= f.label :name, "ユーザーネーム" %>
        <%= f.text_field :name, class:"form-control" %>
        
        <%= f.label :email, "メールアドレス" %>
        <%= f.text_field :email, class:"form-control" %>
        
        <%= f.label :profile, "プロフィール" %>
        <%= f.text_field :profile, class:"form-control" %>
        
        <%= f.submit :"プロフィールを更新", class: "btn btn-large btn-warning" %>
    <% end %>
    </div>
</div>

app/views/users/favorites.html.erb
<h1>お気に入りのHike</h1>
<ul style="list-style:none;">
<li>
<%= render @favorites %>
</li>
</ul>

app/views/users/followers.html.erb
<h1>フォローされているユーザー</h1>
<br>

<% @fs_user.each do |user| %>
   <ul style="list-style:none;">
   <li>
   <%= gravatar_for(user) %>
   <%= link_to user.name, user %>
   </li>
   </ul>
<% end %>

app/views/users/followings.html.erb
<h1>フォロー中のユーザー</h1>
<br>

<% @f_user.each do |user| %>
   <ul style="list-style:none;">
   <li>
   <%= gravatar_for(user) %>
   <%= link_to user.name, user %>
   </li>
   </ul>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワードの再確認" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "アカウントを作成する", class: "btn btn-large btn-warning" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
        <%= @user.profile %><br>
        <%= link_to 'フォロー中のHiker', followings_user_path(@user.id) %><br>
        <%= link_to 'フォローされているHiker', followers_user_path(@user.id) %><br>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.hikes.any? %>
      <h3><%= @user.hikes.count %>件のHikes</h3>
      <ol class="hikes">
        <%= render @hikes %>
      </ol>
    <% end %>
  </div>
</div>